### PR TITLE
Fix the scope of resample.py

### PR DESCRIPTION
**Pull request by Tps-F**
### Overview
The variable written to `if __name__ == "__main__"` becomes a global variable and does not need to be passed as a function argument.

### About the Change
Removed the global variable `args`, `speakers` from the argument

### CODE REVIEW

**Comment by Chaojiu** [comment]
The new resample.py doesn't output any file or folder.
```
PS D:\so-vits-svc-4.1-Stable> python resample.py
CPU count: 12
./dataset_raw\goldship
100%|███████████████████████████████████████████████████████████████████████████████| 737/737 [00:02<00:00, 345.66it/s]
PS D:\so-vits-svc-4.1-Stable>

```

The old resample.py I downloaded from branch 4.0 works well. It will create dataset and 44k folders and output resampled files.

```
PS D:\so-vits-svc-4.1-Stable> python resample.py
./dataset_raw\goldship
737it [00:13, 53.09it/s]
PS D:\so-vits-svc-4.1-Stable>
```
Environment: windows 10, python 3.10.4

**Comment by Tps-F** [comment]
@Chaojiu The last modification was not included in the PR. I apologize for any inconvenience this may have caused.

**Comment by Tps-F** [comment]
Commits that were not included were sent out to #256
Would you try it?

**Comment by Chaojiu** [comment]
@Tps-F It's working well now. Thank you for fixing it so quickly.

**Pull request merged**
